version: '3.8'
services:
    web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - 8000:8000
      depends_on:
        - db
      environment:
        - "DJANGO_SECRET_KEY=django-insecure-rwdbcy&_)#d188lh^85kkst7o&(#)2r%k)0azu-uvxicbh2!^m"
        - "DJANGO_DEBUG=True"
        - "DJANGO_SECURE_HSTS_SECONDS=0"
        - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
        - "DJANGO_SECURE_HSTS_PRELOAD=False"
        - "DJANGO_SESSION_COOKIE_SECURE=False"
        - "DJANGO_CSRF_COOKIE_SECURE=False"
    db:
      image: postgres:12.3
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
        - "DJANGO_SECURE_SSL_REDIRECT=False"
volumes:
    postgres_data: